// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddUserToOrganization = `-- name: AddUserToOrganization :exec
INSERT INTO user_organization (organization_id, user_id, role) VALUES ($1, $2, $3)
`

type AddUserToOrganizationParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
}

func (q *Queries) AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) error {
	_, err := q.db.Exec(ctx, AddUserToOrganization, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}

const CreateAccount = `-- name: CreateAccount :one
INSERT INTO smtp_accounts (organization_id, username)
VALUES ($1, $2) RETURNING id, organization_id, username, created_at
`

type CreateAccountParams struct {
	OrganizationID pgtype.UUID
	Username       string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (SmtpAccount, error) {
	row := q.db.QueryRow(ctx, CreateAccount, arg.OrganizationID, arg.Username)
	var i SmtpAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}

const CreateAuthMethod = `-- name: CreateAuthMethod :one
INSERT INTO smtp_auth_methods (account_id, type, hash, description, expires_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id, account_id, type, hash, description, expires_at, created_at
`

type CreateAuthMethodParams struct {
	AccountID   pgtype.UUID
	Type        string
	Hash        string
	Description string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateAuthMethod(ctx context.Context, arg CreateAuthMethodParams) (SmtpAuthMethod, error) {
	row := q.db.QueryRow(ctx, CreateAuthMethod,
		arg.AccountID,
		arg.Type,
		arg.Hash,
		arg.Description,
		arg.ExpiresAt,
	)
	var i SmtpAuthMethod
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Hash,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, is_admin) VALUES ($1, $2, $3) RETURNING id, email, password_hash, is_admin, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.Email, arg.PasswordHash, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteAuthMethod = `-- name: DeleteAuthMethod :exec
DELETE FROM smtp_auth_methods WHERE id = $1
`

func (q *Queries) DeleteAuthMethod(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteAuthMethod, id)
	return err
}

const GetAccountByUsername = `-- name: GetAccountByUsername :one
SELECT a.id, a.organization_id, a.username, a.created_at, o.slug AS organization_slug
FROM smtp_accounts a
JOIN organizations o ON o.id = a.organization_id
WHERE a.username = $1 LIMIT 1
`

type GetAccountByUsernameRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	Username         string
	CreatedAt        pgtype.Timestamptz
	OrganizationSlug string
}

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (GetAccountByUsernameRow, error) {
	row := q.db.QueryRow(ctx, GetAccountByUsername, username)
	var i GetAccountByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Username,
		&i.CreatedAt,
		&i.OrganizationSlug,
	)
	return i, err
}

const GetAuthMethodsByAccountID = `-- name: GetAuthMethodsByAccountID :many
SELECT id, account_id, type, hash, description, expires_at, created_at FROM smtp_auth_methods WHERE account_id = $1
`

func (q *Queries) GetAuthMethodsByAccountID(ctx context.Context, accountID pgtype.UUID) ([]SmtpAuthMethod, error) {
	rows, err := q.db.Query(ctx, GetAuthMethodsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmtpAuthMethod
	for rows.Next() {
		var i SmtpAuthMethod
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.Hash,
			&i.Description,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPasswordMethodByAccountID = `-- name: GetPasswordMethodByAccountID :one
SELECT id, account_id, type, hash, description, expires_at, created_at FROM smtp_auth_methods WHERE account_id = $1 AND type = 'password' LIMIT 1
`

func (q *Queries) GetPasswordMethodByAccountID(ctx context.Context, accountID pgtype.UUID) (SmtpAuthMethod, error) {
	row := q.db.QueryRow(ctx, GetPasswordMethodByAccountID, accountID)
	var i SmtpAuthMethod
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Hash,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, is_admin, created_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const RemoveUserFromOrganization = `-- name: RemoveUserFromOrganization :exec
DELETE FROM user_organization WHERE organization_id = $1 AND user_id = $2
`

type RemoveUserFromOrganizationParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) RemoveUserFromOrganization(ctx context.Context, arg RemoveUserFromOrganizationParams) error {
	_, err := q.db.Exec(ctx, RemoveUserFromOrganization, arg.OrganizationID, arg.UserID)
	return err
}
