// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddUserToOrganization = `-- name: AddUserToOrganization :exec
INSERT INTO user_organization (organization_id, user_id, role) VALUES ($1, $2, $3)
`

type AddUserToOrganizationParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
}

func (q *Queries) AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) error {
	_, err := q.db.Exec(ctx, AddUserToOrganization, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}

const CreateSMTPCredential = `-- name: CreateSMTPCredential :one
INSERT INTO smtp_credentials (organization_id, username, password_hash) VALUES ($1, $2, $3) RETURNING id, organization_id, username, password_hash, created_at
`

type CreateSMTPCredentialParams struct {
	OrganizationID pgtype.UUID
	Username       string
	PasswordHash   string
}

func (q *Queries) CreateSMTPCredential(ctx context.Context, arg CreateSMTPCredentialParams) (SmtpCredential, error) {
	row := q.db.QueryRow(ctx, CreateSMTPCredential, arg.OrganizationID, arg.Username, arg.PasswordHash)
	var i SmtpCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, is_admin) VALUES ($1, $2, $3) RETURNING id, email, password_hash, is_admin, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.Email, arg.PasswordHash, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const GetSMTPCredentialByUsername = `-- name: GetSMTPCredentialByUsername :one
SELECT sc.id, sc.organization_id, sc.username, sc.password_hash, sc.created_at, o.slug AS organization_slug
FROM smtp_credentials sc
JOIN organizations o ON o.id = sc.organization_id
WHERE sc.username = $1 LIMIT 1
`

type GetSMTPCredentialByUsernameRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	Username         string
	PasswordHash     string
	CreatedAt        pgtype.Timestamptz
	OrganizationSlug string
}

func (q *Queries) GetSMTPCredentialByUsername(ctx context.Context, username string) (GetSMTPCredentialByUsernameRow, error) {
	row := q.db.QueryRow(ctx, GetSMTPCredentialByUsername, username)
	var i GetSMTPCredentialByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.OrganizationSlug,
	)
	return i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, is_admin, created_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const RemoveUserFromOrganization = `-- name: RemoveUserFromOrganization :exec
DELETE FROM user_organization WHERE organization_id = $1 AND user_id = $2
`

type RemoveUserFromOrganizationParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) RemoveUserFromOrganization(ctx context.Context, arg RemoveUserFromOrganizationParams) error {
	_, err := q.db.Exec(ctx, RemoveUserFromOrganization, arg.OrganizationID, arg.UserID)
	return err
}
