// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailbox.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const DeleteEmail = `-- name: DeleteEmail :exec
DELETE FROM emails WHERE id = $1 AND organization_id = $2
`

type DeleteEmailParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) DeleteEmail(ctx context.Context, arg DeleteEmailParams) error {
	_, err := q.db.Exec(ctx, DeleteEmail, arg.ID, arg.OrganizationID)
	return err
}

const GetEmail = `-- name: GetEmail :one
SELECT id, organization_id, smtp_username, mail_from, rcpt_to, subject, body_html, body_text, headers_json, raw_eml, has_attachments, read, received_at, size_bytes FROM emails WHERE id = $1 AND organization_id = $2 LIMIT 1
`

type GetEmailParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetEmail(ctx context.Context, arg GetEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, GetEmail, arg.ID, arg.OrganizationID)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SmtpUsername,
		&i.MailFrom,
		&i.RcptTo,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.HeadersJson,
		&i.RawEml,
		&i.HasAttachments,
		&i.Read,
		&i.ReceivedAt,
		&i.SizeBytes,
	)
	return i, err
}

const InsertEmail = `-- name: InsertEmail :one
INSERT INTO emails (organization_id, smtp_username, mail_from, rcpt_to, subject, body_html, body_text, headers_json, raw_eml, has_attachments, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, organization_id, smtp_username, mail_from, rcpt_to, subject, body_html, body_text, headers_json, raw_eml, has_attachments, read, received_at, size_bytes
`

type InsertEmailParams struct {
	OrganizationID pgtype.UUID
	SmtpUsername   string
	MailFrom       string
	RcptTo         pgtype.FlatArray[string]
	Subject        string
	BodyHtml       string
	BodyText       string
	HeadersJson    []byte
	RawEml         string
	HasAttachments bool
	SizeBytes      int32
}

func (q *Queries) InsertEmail(ctx context.Context, arg InsertEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, InsertEmail,
		arg.OrganizationID,
		arg.SmtpUsername,
		arg.MailFrom,
		arg.RcptTo,
		arg.Subject,
		arg.BodyHtml,
		arg.BodyText,
		arg.HeadersJson,
		arg.RawEml,
		arg.HasAttachments,
		arg.SizeBytes,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SmtpUsername,
		&i.MailFrom,
		&i.RcptTo,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.HeadersJson,
		&i.RawEml,
		&i.HasAttachments,
		&i.Read,
		&i.ReceivedAt,
		&i.SizeBytes,
	)
	return i, err
}

const ListEmails = `-- name: ListEmails :many
SELECT id, organization_id, smtp_username, mail_from, rcpt_to, subject, body_html, body_text, headers_json, raw_eml, has_attachments, read, received_at, size_bytes FROM emails
WHERE organization_id = $1
ORDER BY received_at DESC
LIMIT $2 OFFSET $3
`

type ListEmailsParams struct {
	OrganizationID pgtype.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListEmails(ctx context.Context, arg ListEmailsParams) ([]Email, error) {
	rows, err := q.db.Query(ctx, ListEmails, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SmtpUsername,
			&i.MailFrom,
			&i.RcptTo,
			&i.Subject,
			&i.BodyHtml,
			&i.BodyText,
			&i.HeadersJson,
			&i.RawEml,
			&i.HasAttachments,
			&i.Read,
			&i.ReceivedAt,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkEmailRead = `-- name: MarkEmailRead :exec
UPDATE emails SET read = $3 WHERE id = $1 AND organization_id = $2
`

type MarkEmailReadParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Read           bool
}

func (q *Queries) MarkEmailRead(ctx context.Context, arg MarkEmailReadParams) error {
	_, err := q.db.Exec(ctx, MarkEmailRead, arg.ID, arg.OrganizationID, arg.Read)
	return err
}

const UnreadCount = `-- name: UnreadCount :one
SELECT COUNT(*) FROM emails WHERE organization_id = $1 AND read = false
`

func (q *Queries) UnreadCount(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, UnreadCount, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
