// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Email struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	SmtpUsername   string
	MailFrom       string
	RcptTo         pgtype.FlatArray[string]
	Subject        string
	BodyHtml       string
	BodyText       string
	HeadersJson    []byte
	RawEml         string
	HasAttachments bool
	Read           bool
	ReceivedAt     pgtype.Timestamptz
	SizeBytes      int32
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
}

type SmtpAccount struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Username       string
	CreatedAt      pgtype.Timestamptz
}

type SmtpAuthMethod struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	Type        string
	Hash        string
	Description string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	IsAdmin      bool
	CreatedAt    pgtype.Timestamptz
}

type UserOrganization struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
}
