// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug) VALUES ($1, $2) RETURNING id, name, slug, created_at
`

type CreateOrganizationParams struct {
	Name string
	Slug string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, CreateOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const GetOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, created_at FROM organizations WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, GetOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const ListOrganizationsByAdmin = `-- name: ListOrganizationsByAdmin :many
SELECT id, name, slug, created_at FROM organizations ORDER BY name
`

func (q *Queries) ListOrganizationsByAdmin(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, ListOrganizationsByAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListOrganizationsByUser = `-- name: ListOrganizationsByUser :many
SELECT o.id, o.name, o.slug, o.created_at, uo.role FROM organizations o
JOIN user_organization uo ON uo.organization_id = o.id
WHERE uo.user_id = $1
`

type ListOrganizationsByUserRow struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	Role      string
}

func (q *Queries) ListOrganizationsByUser(ctx context.Context, userID pgtype.UUID) ([]ListOrganizationsByUserRow, error) {
	rows, err := q.db.Query(ctx, ListOrganizationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsByUserRow
	for rows.Next() {
		var i ListOrganizationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
